Repository UMC-Spring-5th/BackDaBang, pull requests merged in 2023-11, with the labels that each got.

#2 [FEAT] 7주차 미션_벡스
  BackDaBang/src/main/java/umc/BackDaBang/BackDaBangApplication.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Review.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/common/BaseEntity.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/mapping/ReviewAlarm.java
Labels: BEX

#7 [FEAT] 7주차 미션_밈보
  BackDaBang/src/main/java/umc/BackDaBang/domain/Image.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Region.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Store.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/mapping/StoreImage.java
Labels: MIMBO

#12 [FEAT] 8주차 미션_벡스
  BackDaBang/build.gradle
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/ApiResponse.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseErrorCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ErrorResponseDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ReasonDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/ErrorStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/SuccessStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/ExceptionAdvice.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/GeneralException.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/handler/TestHandler.java
  BackDaBang/src/main/java/umc/BackDaBang/converter/TestConverter.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TestService/TestCommandService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TestService/TestCommandServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TestService/TestQueryService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TestService/TestQueryServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/web/controller/TestController.java
  BackDaBang/src/main/java/umc/BackDaBang/web/dto/TestResponse.java
Labels: BEX

#13 [FEAT] 8주차 미션_루시
  BackDaBang/build.gradle
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/ApiResponse.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseErrorCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ErrorReasonDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ReasonDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/ErrorStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/SuccessStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/ExceptionAdvice.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/GeneralException.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/handler/TempHandler.java
  BackDaBang/src/main/java/umc/BackDaBang/converter/TempConverter.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempCommandService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempCommandServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempQueryService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempQueryServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/web/controller/TempRestController.java
  BackDaBang/src/main/java/umc/BackDaBang/web/dto/TempRequest.java
  BackDaBang/src/main/java/umc/BackDaBang/web/dto/TempResponse.java
Labels: LUCY

#24 [FEAT] 8주차 미션 밈보
  BackDaBang/build.gradle
  BackDaBang/src/main/java/umc/BackDaBang/BackDaBangApplication.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/ApiResponse.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/BaseErrorCode.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/CommonErrorStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ErrorReasonDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/ReasonDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/ErrorStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/code/status/SuccessStatus.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/ExceptionAdvice.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/GeneralException.java
  BackDaBang/src/main/java/umc/BackDaBang/apiPayload/exception/handler/TempHandler.java
  BackDaBang/src/main/java/umc/BackDaBang/converter/TempConverter.java
  BackDaBang/src/main/java/umc/BackDaBang/conveter/MemberConverter.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/FoodType.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Inquiry.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/InquiryAlarm.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/InquiryImage.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Member.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Mission.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/MissionAlarm.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Region.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Review.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/ReviewAlarm.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/ReviewImage.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/Store.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/StoreImage.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/common/BaseEntity.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/enums/Gender.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/enums/SocialType.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/mapping/MemberFoodType.java
  BackDaBang/src/main/java/umc/BackDaBang/domain/mapping/MemberMission.java
  BackDaBang/src/main/java/umc/BackDaBang/dto/MemberRequestDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/dto/MemberResponseDTO.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempService/TempCommandService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempService/TempCommandServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempService/TempQueryService.java
  BackDaBang/src/main/java/umc/BackDaBang/service/TempService/TempQueryServiceImpl.java
  BackDaBang/src/main/java/umc/BackDaBang/web/controller/TempRestController.java
  BackDaBang/src/main/java/umc/BackDaBang/web/dto/TempRequest.java
  BackDaBang/src/main/java/umc/BackDaBang/web/dto/TempResponse.java
Labels: MIMBO
